made changes to rbac files

diff --git a/Jenkinsfile_rbac b/Jenkinsfile_rbac
--- a/Jenkinsfile_rbac
+++ b/Jenkinsfile_rbac
@@ -37,7 +37,14 @@ pipeline {
         stage('RBAC Syntax Check') {
             steps {
                 script {
-                    sh 'ansible-playbook -v rbac/rbac.yml --syntax-check'
+                    sh '''
+                        if [ -f rbac/rbac.yml ]; then
+                            ansible-playbook -v rbac/rbac.yml --syntax-check
+                        else
+                            echo "ERROR: rbac/rbac.yml not found in repository"
+                            exit 1
+                        fi
+                    '''
                 }
                 echo 'RBAC playbook syntax checked'
             }
@@ -45,7 +52,14 @@ pipeline {
         stage('RBAC Test') {
             steps {
                 script {
-                    sh 'ansible-playbook rbac/rbac.yml --check'
+                    sh '''
+                        if [ -f rbac/rbac.yml ]; then
+                            ansible-playbook rbac/rbac.yml --check
+                        else
+                            echo "ERROR: rbac/rbac.yml not found in repository"
+                            exit 1
+                        fi
+                    '''
                 }
                 echo 'RBAC configuration tested'
             }
@@ -53,7 +67,14 @@ pipeline {
         stage('RBAC Deploy') {
             steps {
                 script {
-                    sh 'ansible-playbook rbac/rbac.yml'
+                    sh '''
+                        if [ -f rbac/rbac.yml ]; then
+                            ansible-playbook rbac/rbac.yml
+                        else
+                            echo "ERROR: rbac/rbac.yml not found in repository"
+                            exit 1
+                        fi
+                    '''
                 }
                 echo 'RBAC configuration deployed successfully'
             }
@@ -67,7 +88,14 @@ pipeline {
             }
             steps {
                 withSonarQubeEnv(installationName: 'SonarCloud') {
-                    sh "cd rbac && ${scannerHome}/bin/sonar-scanner -X"
+                    sh '''
+                        if [ -d rbac ]; then
+                            cd rbac && ${scannerHome}/bin/sonar-scanner -X
+                        else
+                            echo "ERROR: rbac directory not found"
+                            exit 1
+                        fi
+                    '''
                 }
                 echo 'SonarQube analysis completed for RBAC'
             }
